package dev.pam.subscriptions
import android.content.Context
import androidx.activity.ComponentActivity
import com.android.billingclient.api.*
import dev.pam.nativeapp.modules.*
import dev.pam.nativeapp.protocol.*
import org.json.JSONArray
class SubscriptionsModule(context:Context):NativeModule,PurchasesUpdatedListener{
 private val activity=context as? ComponentActivity;private var purchaseCompletion:ModuleCompletion?=null
 private val client=BillingClient.newBuilder(context.applicationContext).setListener(this).enablePendingPurchases(PendingPurchasesParams.newBuilder().enableOneTimeProducts().build()).build()
 override fun invoke(method:String,payload:ByteArray,completion:ModuleCompletion){val values=runCatching{WireMap.decode(payload)}.getOrElse{completion.fail(it.message.orEmpty());return};ready(completion){when(method){"products"->products(values,completion);"purchase"->purchase(values,completion);"restore"->restore(completion);"acknowledge"->acknowledge(values,completion);else->completion.fail("Unknown method: $method")}}}
 private fun ready(completion:ModuleCompletion,action:()->Unit){if(client.isReady){action();return};client.startConnection(object:BillingClientStateListener{override fun onBillingServiceDisconnected(){};override fun onBillingSetupFinished(result:BillingResult){if(result.responseCode==BillingClient.BillingResponseCode.OK)action()else completion.fail(result.debugMessage)}})}
 private fun products(v:Map<String,WireValue>,completion:ModuleCompletion){val ids=JSONArray(v.text("ids"));val list=(0 until ids.length()).map{QueryProductDetailsParams.Product.newBuilder().setProductId(ids.getString(it)).setProductType(BillingClient.ProductType.SUBS).build()};client.queryProductDetailsAsync(QueryProductDetailsParams.newBuilder().setProductList(list).build()){result,details->if(result.responseCode!=BillingClient.BillingResponseCode.OK){completion.fail(result.debugMessage);return@queryProductDetailsAsync};val rows=JSONArray();for(product in details.productDetailsList){val offers=product.subscriptionOfferDetails.orEmpty();if(offers.isEmpty())rows.put(productRow(product,"",""));else for(offer in offers){val price=offer.pricingPhases.pricingPhaseList.lastOrNull()?.formattedPrice.orEmpty();rows.put(productRow(product,offer.offerToken,price))}};completion.ok(mapOf("json" to WireValue.Text(rows.toString())))}}
 private fun productRow(p:ProductDetails,token:String,price:String)=org.json.JSONObject().put("id",p.productId).put("title",p.title).put("description",p.description).put("price",price).put("offerToken",token)
 private fun purchase(v:Map<String,WireValue>,completion:ModuleCompletion){val a=activity;if(a==null){completion.fail("Subscriptions require an Activity context.");return};val id=v.text("productId");val requested=v.text("offerToken");val q=QueryProductDetailsParams.newBuilder().setProductList(listOf(QueryProductDetailsParams.Product.newBuilder().setProductId(id).setProductType(BillingClient.ProductType.SUBS).build())).build();client.queryProductDetailsAsync(q){result,details->val product=details.productDetailsList.firstOrNull();if(result.responseCode!=BillingClient.BillingResponseCode.OK||product==null){completion.fail(result.debugMessage.ifEmpty{"Product not found."});return@queryProductDetailsAsync};val offer=product.subscriptionOfferDetails.orEmpty().firstOrNull{requested.isEmpty()||it.offerToken==requested};if(offer==null){completion.fail("Subscription offer not found.");return@queryProductDetailsAsync};purchaseCompletion=completion;val params=BillingFlowParams.ProductDetailsParams.newBuilder().setProductDetails(product).setOfferToken(offer.offerToken).build();val launch=client.launchBillingFlow(a,BillingFlowParams.newBuilder().setProductDetailsParamsList(listOf(params)).build());if(launch.responseCode!=BillingClient.BillingResponseCode.OK){purchaseCompletion=null;completion.fail(launch.debugMessage)}}}
 override fun onPurchasesUpdated(result:BillingResult,purchases:MutableList<Purchase>?){val completion=purchaseCompletion?:return;purchaseCompletion=null;if(result.responseCode==BillingClient.BillingResponseCode.USER_CANCELED){completion.ok(transaction("","","",3));return};val p=purchases?.firstOrNull();if(result.responseCode!=BillingClient.BillingResponseCode.OK||p==null){completion.fail(result.debugMessage);return};completion.ok(transaction(p.products.firstOrNull().orEmpty(),p.orderId.orEmpty(),p.purchaseToken,if(p.purchaseState==Purchase.PurchaseState.PENDING)2 else 1))}
 private fun restore(completion:ModuleCompletion){client.queryPurchasesAsync(QueryPurchasesParams.newBuilder().setProductType(BillingClient.ProductType.SUBS).build()){result,purchases->if(result.responseCode!=BillingClient.BillingResponseCode.OK){completion.fail(result.debugMessage);return@queryPurchasesAsync};val rows=JSONArray();purchases.forEach{rows.put(org.json.JSONObject(transaction(it.products.firstOrNull().orEmpty(),it.orderId.orEmpty(),it.purchaseToken,if(it.purchaseState==Purchase.PurchaseState.PENDING)2 else 1).mapValues{x->when(val value=x.value){is WireValue.Text->value.value;is WireValue.Integer->value.value;else->""}}))};completion.ok(mapOf("json" to WireValue.Text(rows.toString())))}}
 private fun acknowledge(v:Map<String,WireValue>,completion:ModuleCompletion){client.acknowledgePurchase(AcknowledgePurchaseParams.newBuilder().setPurchaseToken(v.text("verification")).build()){if(it.responseCode==BillingClient.BillingResponseCode.OK)completion.ok()else completion.fail(it.debugMessage)}}
 private fun transaction(product:String,id:String,token:String,state:Long)=mapOf("productId" to WireValue.Text(product),"transactionId" to WireValue.Text(id),"verification" to WireValue.Text(token),"state" to WireValue.Integer(state));private fun Map<String,WireValue>.text(k:String)=(get(k)as?WireValue.Text)?.value.orEmpty();private fun ModuleCompletion.ok(v:Map<String,WireValue> = emptyMap())=complete(ModuleResultStatus.SUCCESS,WireMap.encode(v));private fun ModuleCompletion.fail(m:String)=complete(ModuleResultStatus.FAILURE,m.take(1024).toByteArray())
}
