import Foundation
import PamNative
import StoreKit
public final class SubscriptionsModule:NativeModule,@unchecked Sendable{
 public init(){}
 public func invoke(method:String,payload:Data,completion:@escaping ModuleCompletion){do{let v=try WireMap.decode(payload);switch method{case"products":products(v,completion);case"purchase":purchase(v,completion);case"restore":restore(completion);case"acknowledge":acknowledge(v,completion);default:failure("Unknown method: \(method)",completion)}}catch{failure(String(describing:error),completion)}}
 private func products(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion){Task{do{let ids=try JSONDecoder().decode([String].self,from:Data(try v.text("ids").utf8));let products=try await Product.products(for:ids);let rows=products.map{p in["id":p.id,"title":p.displayName,"description":p.description,"price":p.displayPrice,"offerToken":""]};try success(["json":.text(String(data:try JSONSerialization.data(withJSONObject:rows),encoding:.utf8)!)],completion:completion)}catch{failure(String(describing:error),completion)}}}
 private func purchase(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion){Task{do{let id=try v.text("productId");guard let product=try await Product.products(for:[id]).first else{throw StoreError.notFound};let result=try await product.purchase();switch result{case.success(let verification):switch verification{case.verified(let transaction):try success(transactionMap(transaction,state:1),completion:completion);case.unverified(_,let error):failure(error.localizedDescription,completion)};case.pending:try success(["productId":.text(id),"transactionId":.text(""),"verification":.text(""),"state":.integer(2)],completion:completion);case.userCancelled:try success(["productId":.text(id),"transactionId":.text(""),"verification":.text(""),"state":.integer(3)],completion:completion);@unknown default:failure("Unknown StoreKit purchase result.",completion)}}catch{failure(String(describing:error),completion)}}}
 private func restore(_ completion:@escaping ModuleCompletion){Task{do{try await AppStore.sync();var rows:[[String:Any]]=[];for await entitlement in Transaction.currentEntitlements{if case.verified(let t)=entitlement{rows.append(["productId":t.productID,"transactionId":String(t.id),"verification":t.jwsRepresentation,"state":1])}};try success(["json":.text(String(data:try JSONSerialization.data(withJSONObject:rows),encoding:.utf8)!)],completion:completion)}catch{failure(String(describing:error),completion)}}}
 private func acknowledge(_ v:[String:WireValue],_ completion:@escaping ModuleCompletion){Task{do{let id=try v.text("transactionId");for await result in Transaction.unfinished{if case.verified(let transaction)=result,String(transaction.id)==id{await transaction.finish();try success(completion:completion);return}};throw StoreError.notFound}catch{failure(String(describing:error),completion)}}}
 private func transactionMap(_ t:Transaction,state:Int64)->[String:WireValue]{["productId":.text(t.productID),"transactionId":.text(String(t.id)),"verification":.text(t.jwsRepresentation),"state":.integer(state)]}
 private func success(_ values:[String:WireValue]=[:],completion:ModuleCompletion)throws{completion(.success,try WireMap.encode(values))};private func failure(_ message:String,_ completion:ModuleCompletion){completion(.failure,Data(message.prefix(1024).utf8))}
}
private enum StoreError:Error{case notFound}
private extension Dictionary where Key==String,Value==WireValue{func text(_ key:String)throws->String{guard case let.text(value)?=self[key]else{throw StoreError.notFound};return value}}
